# Clear a region specified by a global axis-aligned bounding box in stored OctoMap

# minimum corner point of axis-aligned bounding box in global frame
geometry_msgs/Point min
# maximum corner point of axis-aligned bounding box in global frame
geometry_msgs/Point max
---

