# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
sudo: required
language: generic
env:
  global:
    - ROS_PARALLEL_JOBS=-j4 # Don't exhaust virtual memory
  matrix:
    - ROS_DISTRO="kinetic" CATKIN_CONFIG='-DCMAKE_BUILD_TYPE=Debug'
    - ROS_DISTRO="kinetic" CATKIN_CONFIG='-DCMAKE_BUILD_TYPE=Release'
    - ROS_DISTRO="kinetic" PRERELEASE=true
    - ROS_DISTRO="melodic" CATKIN_CONFIG='-DCMAKE_BUILD_TYPE=Debug'
    - ROS_DISTRO="melodic" CATKIN_CONFIG='-DCMAKE_BUILD_TYPE=Release'
    - ROS_DISTRO="melodic" PRERELEASE=true
    - ROS_DISTRO="melodic" OS_NAME="debian" OS_CODE_NAME="stretch"
matrix:
  allow_failures:
    - env: ROS_DISTRO="kinetic" PRERELEASE=true
    - env: ROS_DISTRO="melodic" PRERELEASE=true
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
