name: Industrial-CI
on: [push, pull_request] # on all pushes and PRs

jobs:
  CI:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: rolling}
          - {ROS_DISTRO: humble, PRERELEASE: true}
          - {ROS_DISTRO: iron, PRERELEASE: true}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
