name: ROS2 CI

on:
  pull_request:
    branches:
      - 'ros2'

jobs:
  test_environment:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
          - iron
          - rolling
        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - os: ubuntu-22.04
            ros_distribution: humble
            ros_version: 2
          # Iron Irwini (May 2023 - November 2024)
          - os: ubuntu-22.04
            ros_distribution: iron
            ros_version: 2
          # Rolling Ridley  (June 2020 - Present)
          - os: ubuntu-22.04
            ros_distribution: rolling
            ros_version: 2
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.ros_distribution == 'rolling' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Search packages in this repository
        id: list_packages
        run: |
          echo ::set-output name=package_list::$(colcon list --names-only)

      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.3.6
        with:
          package-name: ${{ steps.list_packages.outputs.package_list }}
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: build_depends.repos
